# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  staticDir: static
  title: SHUD Group
  params:
    description: SHUD Group
  menu:
    main:
      - name: Home
        url: '#home'
        weight: 1
      - name: SHUD Model
        url: 'https://shud.xyz/book_en'
        weight: 10
      - name: Project
        url: 'project'
        weight: 20
      - name: People
        url: 'team'
        weight: 30
      - name: Publications
        url: 'publication'
        weight: 40
      - name: Course
        url: 'course/'
        weight: 70
      - name: Global Hydro Cloud
        url: 'https://shuddata.com'
        weight: 80
      - name: Gallery
        url: 'https://shudapp.netlify.app'
        weight: 90
      - name: Join Us
        url: 'opp'
        weight: 99

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-CN
  contentDir: content/zh
  staticDir: static
  title: SHUD研究组
  params:
    description: SHUD模型研究组
  menu:
    main:
      - name: 首页
        url: '#home'
        weight: 1
      - name: SHUD模型
        url: 'https://shud.xyz/book_cn'
        weight: 10
      - name: 项目
        url: 'project'
        weight: 20
      - name: 团队
        url: 'team/'
        weight: 30
      - name: 论文
        url: 'publication/'
        weight: 50
      - name: 书籍/课程
        url: 'course/'
        weight: 70
      - name: 全球水文数据云
        url: 'https://shuddata.com'
        weight: 80
      - name: 图库
        url: 'https://shudapp.netlify.app'
        weight: 80
      - name: 加入我们
        url: 'opp/'
        weight: 99
