# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: Ocean
  theme_night: Ocean
  font: Classic
  font_size: m

# SEO

marketing:
  seo:
    site_type: ResearchOrganization
    local_business_type: 'Academic'
    org_name: 'SHUD research group'
    description: 'Academic research group, Simulator of Hydrologic Unstructured Domains'
    twitter: 'leleshu'
  analytics:
    google_analytics: 'UA-153411227-1'
    baidu_tongji: '02eaeeb22ebc1b673b5317dd3fc030c4'
  verification:
    google: ''
    baidu: 'code-caLY3Fu6xB'

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: true
    show_day_night: false
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {2022} SHUD. 凡我公开的，皆不保留版权，亦不申索权益；但需要您合理引用。 (I reserve no right on anything in this website. Use it for free with right citation/reference. )'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Citation style

publications:
  date_format: January 2006
  citation_style: apa
